### ISSUE TITLE
How to set up this software？

### ISSUE THREAD

**Issue by XZYuann** [goxr3plus/XR3Player#72] opened 2020-04-19 01:43 UTC
It seems that i am getting trouble setting up it.
![image](https://user-images.githubusercontent.com/54098964/79677285-36510600-8222-11ea-9e9c-30e8e53ad0e2.png)
![image](https://user-images.githubusercontent.com/54098964/79677289-3a7d2380-8222-11ea-8fa8-b418abfbfc23.png)

**Comment by goxr3plus** [comment] 2020-04-22 11:06
Oouu that's really bad .

You have Windows 10 ?
Do you have any Java Version installed already :) ?
You downloaded from here => https://xr3player.netlify.app/ ?

Are you admin or simple user :) ?

Gosh i have to update this program it's been 1 year :)

**Comment by xzYuann** [comment] 2020-04-22 11:25
1.yes，Windows 10

2.this is my Java version

3.from here

4.I'm a freshman majoring in computer science.
&nbsp;My java teacher recommended me to learn your software, but I don't know how to start it. When it's half installed, it always shows errors
I have communicated with some other students, and they have reported that they have also encountered this problem.How can I solve this problem？



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Alexander Kentros"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 晚上7:06
收件人:&nbsp;"goxr3plus/XR3Player"<XR3Player@noreply.github.com&gt;;
抄送:&nbsp;"会飞的鱼"<3494300360@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [goxr3plus/XR3Player] How to set up this software？ (#72)





 
Oouu that's really bad .
 
You have Windows 10 ?
 Do you have any Java Version installed already :) ?
 You downloaded from here =&gt; https://xr3player.netlify.app/ ?
 
Are you admin or simple user :) ?
 
Gosh i have to update this program it's been 1 year :)

**Comment by goxr3plus** [comment] 2020-04-22 11:36
@xzYuann Really your teacher recommended you to learn my software :) ?

Well look you want just to run it or study the code :) ? 

All the students in the class have the same problem with the download procedure :) ? 

I am downloading it my self now to see what's the problem .

**Comment by goxr3plus** [comment] 2020-04-22 11:38
First you see the install window don't you?

![image](https://user-images.githubusercontent.com/20374208/79977383-dd45d400-84a6-11ea-982a-97a0c2b2a250.png)

**Comment by goxr3plus** [comment] 2020-04-22 11:38
The software is trying to download Java 8 or 10 if i am not wrong for XR3Player.

**Comment by goxr3plus** [comment] 2020-04-22 11:43
Then you get a prompt window you press yes ,

then this appears 

![image](https://user-images.githubusercontent.com/20374208/79977497-07979180-84a7-11ea-9666-01744f1c10d3.png)

you press next and then I accept the agreement , next , then you choose the installation folder , next :

![XR3Player_Installer_2020-04-22_14-39-30](https://user-images.githubusercontent.com/20374208/79977591-3281e580-84a7-11ea-9aff-1242cea978cb.png)

![XR3Player_Installer_2020-04-22_14-39-48](https://user-images.githubusercontent.com/20374208/79977598-33b31280-84a7-11ea-8912-40a8cf3b6b45.png)

![XR3Player_Installer_2020-04-22_14-39-56](https://user-images.githubusercontent.com/20374208/79977601-357cd600-84a7-11ea-99d0-01827a976e5b.png)

![image](https://user-images.githubusercontent.com/20374208/79977620-3d3c7a80-84a7-11ea-92de-b76b63655cbf.png)

![image](https://user-images.githubusercontent.com/20374208/79977811-85f43380-84a7-11ea-95bb-dd158e13817b.png)

**Comment by goxr3plus** [comment] 2020-04-22 11:43
I just installed it with no problems ... are you using your own computer or computer from University labs :) ?

**Comment by xzYuann** [comment] 2020-04-22 13:13
> First you see the install window don't you?
> 





> First you see the install window don't you?
> 
> ![image](https://user-images.githubusercontent.com/20374208/79977383-dd45d400-84a6-11ea-982a-97a0c2b2a250.png)

![image](https://user-images.githubusercontent.com/54098964/79986064-0fbef380-84de-11ea-842e-f9bf0e777a90.png)

**Comment by xzYuann** [comment] 2020-04-22 13:19
> > First you see the install window don't you?
> 
> > First you see the install window don't you?
> > ![image](https://user-images.githubusercontent.com/20374208/79977383-dd45d400-84a6-11ea-982a-97a0c2b2a250.png)
> 
> ![image](https://user-images.githubusercontent.com/54098964/79986064-0fbef380-84de-11ea-842e-f9bf0e777a90.png)



> @xzYuann Really your teacher recommended you to learn my software :) ?
> I am really happy that somebody noticed XR3Player :) from the community .
> I am also a College Student by the way but not freshman :)
> 
> Well look you want just to run it or study the code :) ?
> 
> All the students in the class have the same problem with the download procedure :) ?
> 
> I am downloading it my self now to see what's the problem .
I want to study the code，yet


> I just installed it with no problems ... are you using your own computer or computer from University labs :) ?
Maybe my local network is not good, or there is a firewall to stop it

**Comment by goxr3plus** [comment] 2020-04-22 13:29
I think it has to do something with 

1) Network 
2) Firewall 
3) Admin rights on computer 

All your friends have the same problem downloading it ? It's your own computer and you download from house right ?  Can you send me that .log file showing on the error screen it has the actual error . 

C:\USERS\34943 .... ETC send me please that file :)

**Comment by xzYuann** [comment] 2020-04-22 14:26
Started executable D:\BaiduNetdiskDownload\XR3Player_Installer.exe at Wed Apr 22 22:24:50 2020


[0:0] restrict DLL directories
[0:5] init file name D:\BaiduNetdiskDownload\XR3Player_Installer.exe D:\BaiduNetdiskDownload\XR3Player_Installer.exe 47 0
[0:6] number of sections: 6
[0:8] size of optional headers: 240
[0:9] resSectionTableStart: 720
[0:11] rawDataSize: 2560, rawDataOffset: 461824
[0:13] sun.locale.formatasdefault is false
[0:14] language/country is zh_CN
[0:20] change working directory to D:\BaiduNetdiskDownload
[0:21] single instance mode
[0:22] semaphore name Local\d:_baidunetdiskdownload_xr3player_installer.exe, code 0, value 0000000000000150
[0:24] Init done
[0:63] Starting work
[0:88] number of sections: 6
[0:89] size of optional headers: 240
[0:90] resSectionTableStart: 720
[0:92] rawDataSize: 2560, rawDataOffset: 461824
[0:93] starting at 464384
[0:95] verifying integrity length 78627551
[0:360] checksums: 3633997258 3633997258 -660970038 -660970038
[0:361] tempPath is C:\Users\34943\AppData\Local\Temp\
[0:362] tempFile is C:\Users\34943\AppData\Local\Temp\e4j884B.tmp
[0:363] Temp dir3: C:\Users\34943\AppData\Local\Temp\e4j884B.tmp_dir1587565491
[0:365] native lib dir is ${launcher:sys.launcherTempDirectory}\user
[0:366] expanding2 ${launcher:sys.launcherTempDirectory} to C:\Users\34943\AppData\Local\Temp\e4j884B.tmp_dir1587565491 in C:\Users\34943\AppData\Local\Temp\e4j884B.tmp_dir1587565491\user.
[0:367] Adding DLL directory C:\Users\34943\AppData\Local\Temp\e4j884B.tmp_dir1587565491\user
[0:368] Setting PATH (native libs) C:\Users\34943\AppData\Local\Temp\e4j884B.tmp_dir1587565491\user;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Java\jdk1.8.0_221\bin;C:\Program Files\Java\jdk1.8.0_221\jre\bin;C:\WINDOWS\system32;C:\Users\34943\Desktop\mysql8.0.14_downcc.com\mysql8.0.14_downcc.com\mysql8.0.14winx64_downcc.com\bin;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\BaiduNetdiskDownload\MinGW64;;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\34943\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.1\ÐÂ½¨ÎÄ¼þ¼Ð\IntelliJ IDEA 2019.3.1\bin;;C:\Users\34943\AppData\Local\Microsoft\WindowsApps;
[0:369] extracting files
[0:370] Included files: 12
[0:371] extracting C:\Users\34943\AppData\Local\Temp\e4j884B.tmp_dir1587565491\i4jruntime.jar.pack (size: 808977)
[0:376] extracting C:\Users\34943\AppData\Local\Temp\e4j884B.tmp_dir1587565491\i4jparams.conf (size: 68566)
[0:378] extracting C:\Users\34943\AppData\Local\Temp\e4j884B.tmp_dir1587565491\installer.ico (size: 22646)
[0:381] extracting C:\Users\34943\AppData\Local\Temp\e4j884B.tmp_dir1587565491\MessagesDefault (size: 33730)
[0:382] extracting C:\Users\34943\AppData\Local\Temp\e4j884B.tmp_dir1587565491\user.jar.pack (size: 2111)
[0:384] extracting C:\Users\34943\AppData\Local\Temp\e4j884B.tmp_dir1587565491\i4j_extf_3_f4lhk3_q63xy.png (size: 930)
[0:385] extracting C:\Users\34943\AppData\Local\Temp\e4j884B.tmp_dir1587565491\i4j_extf_2_f4lhk3.txt (size: 7816)
[0:387] extracting C:\Users\34943\AppData\Local\Temp\e4j884B.tmp_dir1587565491\stats.properties (size: 594)
[0:388] extracting C:\Users\34943\AppData\Local\Temp\e4j884B.tmp_dir1587565491\i4j_extf_1_f4lhk3_1npdbvv.png (size: 2986)
[0:390] extracting C:\Users\34943\AppData\Local\Temp\e4j884B.tmp_dir1587565491\i4j_extf_5_f4lhk3_1vncod6.png (size: 2820)
[0:392] extracting C:\Users\34943\AppData\Local\Temp\e4j884B.tmp_dir1587565491\i4j_extf_0_f4lhk3.utf8 (size: 33730)
[0:393] extracting C:\Users\34943\AppData\Local\Temp\e4j884B.tmp_dir1587565491\i4j_extf_4_f4lhk3_y187my.png (size: 77879)
[0:395] extracting files done
[0:396] Current working dir: C:\Users\34943\AppData\Local\Temp\e4j884B.tmp_dir1587565491
[0:397] Full JRE path: C:\Users\34943\AppData\Local\Temp\e4j884B.tmp_dir1587565491\jre.tar.gz
[0:398] No JRE included
[0:399] LoadDLL (0, (null), 0)
[0:400] Searching for a JVM
[0:401] MinVersion: 10.0.2, MaxVersion: 10.0.2
[0:403] Testing location&nbsp; (type Y)
[0:406] Testing location JAVA_HOME (type E)
[0:407] checkJavaExe (C:\Program Files\Java\jdk1.8.0_221\jre\bin\java.exe, [out], 3, 3, 0)
[0:408] file exists
[0:409] got version from registry 1.8.0_221
[0:410] checkJavaExe returning 0
[0:412] Testing location JDK_HOME (type E)
[0:413] checking app id allinstdirs8282-0762-8339-5307 (0, FFFFFFFF80000001)
[0:414] could not query value node 0
[0:414] checking app id allinstdirs8282-0762-8339-5307 (256, FFFFFFFF80000001)
[0:415] could not query value node 0
[0:416] checking app id allinstdirs8282-0762-8339-5307 (0, FFFFFFFF80000002)
[0:418] could not query value node 0
[0:419] checking app id allinstdirs8282-0762-8339-5307 (256, FFFFFFFF80000002)
[0:421] could not query value node 0
[0:422] Search sequence finished
[0:423] ERROR: No JVM found
[0:425] Download location: https://github.com/goxr3plus/XR3Player-Installers/raw/master/windows-amd64-10.0.2.tar.gz
[0:426] Downloading JRE
[9:244] ERROR: InternetOpenUrl failed with error code 12007
[10:248] ERROR: Retry JRE download
[22:724] ERROR: InternetOpenUrl failed with error code 12007
[23:726] ERROR: Retry JRE download
[37:820] ERROR: InternetOpenUrl failed with error code 12007
[38:822] ERROR: Retry JRE download





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Alexander Kentros"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 晚上9:29
收件人:&nbsp;"goxr3plus/XR3Player"<XR3Player@noreply.github.com&gt;;
抄送:&nbsp;"会飞的鱼"<3494300360@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [goxr3plus/XR3Player] How to set up this software？ (#72)





 
I think it has to do something with
  
Network
 
Firewall
 
Admin rights on computer
  
All your friends have the same problem downloading it ? It's your own computer and you download from house right ?  Can you send me that .log file showing on the error screen it has the actual error .
 
C:\USERS\34943 .... ETC send me please that file :)

**Comment by xzYuann** [comment] 2020-04-24 01:45
Yes, thank you very much
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Alexander Kentros"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 晚上9:29
收件人:&nbsp;"goxr3plus/XR3Player"<XR3Player@noreply.github.com&gt;;
抄送:&nbsp;"会飞的鱼"<3494300360@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [goxr3plus/XR3Player] How to set up this software？ (#72)





 
I think it has to do something with
  
Network
 
Firewall
 
Admin rights on computer
  
All your friends have the same problem downloading it ? It's your own computer and you download from house right ?  Can you send me that .log file showing on the error screen it has the actual error .
 
C:\USERS\34943 .... ETC send me please that file :)

**Comment by goxr3plus** [comment] 2020-04-27 08:58
Hm that's indeed strange , the problem is downloading the JRE in your computer, 
there is a workaround on this :

1 ) You can download Java  1.8.0_221 and install it on your computer 

Go [here ](https://www.oracle.com/java/technologies/javase/javase8u211-later-archive-downloads.html#license-lightbox)and download this .exe => jre-8u221-windows-x64.exe

If you install 1.8.0_221 the installer will skip downloading it so you will not have a problem .

or 

You can install IntelliJ or Eclipse and download the repository code for XR3Player and start it from there .

**Comment by xzYuann** [comment] 2020-04-27 09:14
thanks，it works！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Alexander Kentros"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 下午4:58
收件人:&nbsp;"goxr3plus/XR3Player"<XR3Player@noreply.github.com&gt;;
抄送:&nbsp;"会飞的鱼"<3494300360@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [goxr3plus/XR3Player] How to set up this software？ (#72)





 
Hm that's indeed strange , the problem is downloading the JRE in your computer,
 there is a workaround on this :
 
1 ) You can download Java  1.8.0_221 and install it on your computer
 
Go here and download this .exe =&gt; jre-8u221-windows-x64.exe
 
If you install 1.8.0_221 the installer will skip downloading it so you will not have a problem .
 
or
 
You can install IntelliJ or Eclipse and download the repository code for XR3Player and start it from there .

**Comment by goxr3plus** [comment] 2020-04-27 09:15
So how exactly you solved it :) ?

**Comment by xzYuann** [comment] 2020-04-27 09:22
As you suggested,I download the repository code for XR3Player and start it in&nbsp;&nbsp;IntelliJ :)





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Alexander Kentros"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 下午5:16
收件人:&nbsp;"goxr3plus/XR3Player"<XR3Player@noreply.github.com&gt;;
抄送:&nbsp;"会飞的鱼"<3494300360@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [goxr3plus/XR3Player] How to set up this software？ (#72)





 
So how exactly you solved it :) ?

**Comment by xzYuann** [comment] 2020-04-27 09:23
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Alexander Kentros"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 下午5:16
收件人:&nbsp;"goxr3plus/XR3Player"<XR3Player@noreply.github.com&gt;;
抄送:&nbsp;"会飞的鱼"<3494300360@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [goxr3plus/XR3Player] How to set up this software？ (#72)





 
So how exactly you solved it :) ?

**Comment by goxr3plus** [comment] 2020-04-27 18:37
Glad to hear this :)

**Comment by goxr3plus** [comment] 2020-11-08 14:45
Should i close the issue :) ?

**Closed** 2023-07-08 14:55 UTC
Labels: bug
